"use client";

import { useState } from "react";
import { CryptoPayQrBox } from "./CryptoPayQrBox";

type CryptoPayWalletSectionProps = {
  cryptoCurrency: string;
  cryptoAmount: number;
  invoiceId: string;
};

type NetworkKey = "trc20" | "bep20";

const NETWORKS: Record<
  NetworkKey,
  {
    code: string;
    label: string;
    description: string;
    address: string;
  }
> = {
  trc20: {
    code: "TRC20 · TRON",
    label: "TRC20 · TRON",
    description: "Tether USDT TRC-20 · TRON network",
    address: "TAEtcMJZ4YchkL3JtmcsR9JK2KzUbaMrh3",
  },
  bep20: {
    code: "BEP20 · BNB",
    label: "BEP20 · BNB",
    description: "Tether USDT BEP-20 · BNB Smart Chain",
    address: "0x3de11960168e06871057ec26B9393ceA7858D0fE",
  },
};

type SimulatePaidOk = {
  ok: true;
  invoiceId: string;
  status: string;
};

type SimulatePaidError = {
  ok: false;
  error: string;
  details?: string;
};

type SimulatePaidResponse = SimulatePaidOk | SimulatePaidError;

export function CryptoPayWalletSection({
  cryptoCurrency,
  cryptoAmount,
  invoiceId,
}: CryptoPayWalletSectionProps) {
  const [activeNet, setActiveNet] = useState<NetworkKey>("trc20");
  const [copied, setCopied] = useState(false);

  const [isConfirming, setIsConfirming] = useState(false);
  const [confirmError, setConfirmError] = useState<string | null>(null);

  const network = NETWORKS[activeNet];
  const formattedAmount = `${cryptoAmount.toFixed(2)} ${cryptoCurrency}`;
  const qrValue = network.address;

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(network.address);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      // ignore
    }
  }

  // ✅ Демо: подтвердить оплату (имитация вебхука)
  async function handleConfirmDemoPayment() {
    if (!invoiceId || isConfirming) return;

    setIsConfirming(true);
    setConfirmError(null);

    try {
      const res = await fetch("/api/payments/simulate-paid", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ invoiceId }),
      });

      const data = (await res
        .json()
        .catch(() => ({ ok: false, error: "Invalid JSON response" }))) as
        | SimulatePaidResponse
        | { ok: false; error: string; message?: string };

      if (!res.ok) {
        const message =
          "message" in data && typeof data.message === "string"
            ? data.message
            : "error" in data && typeof data.error === "string"
            ? data.error
            : `Request failed: HTTP ${res.status}`;

        throw new Error(message);
      }

      if ("ok" in data && data.ok === false) {
        const msg =
          (data as SimulatePaidError).details ||
          (data as SimulatePaidError).error ||
          "Simulate paid failed";
        throw new Error(msg);
      }

      // ✅ Ничего не редиректим вручную.
      // Статус поймается поллингом и он сам уведёт на /open/pay/success?invoiceId=...
    } catch (e) {
      setConfirmError(e instanceof Error ? e.message : "Unknown error");
    } finally {
      setIsConfirming(false);
    }
  }

  return (
    <section className="rounded-xl border border-slate-200 bg-white shadow-sm p-4 space-y-4">
      <div>
        <h2 className="text-sm font-semibold text-slate-900">Receive USDT</h2>
        <p className="mt-1 text-xs text-slate-500">
          Choose the network you want to use and send exactly{" "}
          <span className="font-medium text-slate-900">{formattedAmount}</span>{" "}
          from your own wallet. In production this address is generated by the
          Swiss payment provider.
        </p>

        {/* ✅ ВАЖНО ДЛЯ ПОНИМАНИЯ: к какому инвойсу относится платеж */}
        <p className="mt-2 text-[11px] text-slate-500">
          Invoice: <span className="font-mono text-slate-900">{invoiceId}</span>
        </p>
      </div>

      {/* Network selector */}
      <div className="inline-flex rounded-full bg-slate-100 p-1 text-[11px]">
        <button
          type="button"
          onClick={() => setActiveNet("trc20")}
          className={`px-3 py-1.5 rounded-full transition ${
            activeNet === "trc20"
              ? "bg-white shadow-sm text-slate-900"
              : "text-slate-500"
          }`}
        >
          TRC20 · TRON
        </button>
        <button
          type="button"
          onClick={() => setActiveNet("bep20")}
          className={`px-3 py-1.5 rounded-full transition ${
            activeNet === "bep20"
              ? "bg-white shadow-sm text-slate-900"
              : "text-slate-500"
          }`}
        >
          BEP20 · BNB
        </button>
      </div>

      {/* Description */}
      <div className="text-xs text-slate-600">
        <p className="font-medium">{network.description}</p>
      </div>

      {/* Address + Copy */}
      <div className="space-y-1 text-xs">
        <p className="text-[11px] text-slate-500">Payment address</p>

        <div className="flex items-center gap-2 rounded-xl bg-slate-900 px-3 py-2.5 text-slate-50">
          <span className="font-mono text-[11px] truncate">
            {network.address}
          </span>

          <button
            type="button"
            onClick={handleCopy}
            className="inline-flex items-center rounded-lg bg-slate-700 px-2 py-1 text-[10px] font-medium hover:bg-slate-600 transition"
          >
            {copied ? "Copied" : "Copy"}
          </button>
        </div>

        <p className="text-[11px] text-slate-400">
          Send only USDT on <span className="font-medium">{network.code}</span>{" "}
          to this address.
        </p>
      </div>

      {/* QR */}
      <CryptoPayQrBox value={qrValue} />

      {/* Notices */}
      <ul className="list-disc list-inside text-[11px] text-slate-500 space-y-1 pt-1">
        <li>Always double-check the address and selected network.</li>
        <li>For larger payments, send a small test transaction first.</li>
        <li>
          This is a demo. In production, payments are processed by a Swiss
          regulated partner.
        </li>
      </ul>

      {/* ✅ CTA: подтверждаем оплату через simulate-paid */}
      <button
        type="button"
        onClick={handleConfirmDemoPayment}
        disabled={isConfirming || !invoiceId}
        className="
          w-full flex items-center justify-center gap-1
          bg-black text-white
          font-medium text-sm
          py-2.5 rounded-xl
          hover:bg-slate-900 active:scale-[0.98]
          transition shadow-sm mt-2
          disabled:opacity-60 disabled:cursor-not-allowed disabled:active:scale-100
        "
      >
        {isConfirming
          ? "Confirming payment (demo)..."
          : "I have sent the payment (demo)"}
        <span className="text-lg leading-none">→</span>
      </button>

      {confirmError && (
        <p className="text-[11px] text-rose-600">
          Demo confirm failed: {confirmError}
        </p>
      )}
    </section>
  );
}
